[package]
name = "db_api_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3"
mysql = "24.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
config = "0.13"
dotenv = "0.15"
thiserror = "1.0"
log = "0.4"
env_logger = "0.10"

